/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cms.project;

import java.util.Random;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Jorg
 */
public class resultsManager extends javax.swing.JFrame {

    
    private String selectedUsername;

    /**
     * Creates new form resultsManager
     */
    public resultsManager(String selectedUsername) {
        initComponents();
        this.selectedUsername = selectedUsername;
        displaySurveyResults();
    }

    
    private void displaySurveyResults() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing rows

        // Retrieve survey results for the selected user from the database
        // You can implement the necessary code to fetch survey results here
        // For example:
        /*
        cConnect connection = new cConnect();
        // Execute a SQL query to retrieve survey results for the selected user
        String query = "SELECT user_id, survey_result FROM survey_results WHERE username = ?";
        PreparedStatement statement = connection.prepareStatement(query);
        statement.setString(1, selectedUsername);
        ResultSet resultSet = statement.executeQuery();

        // Iterate over the result set and add rows to the table model
        while (resultSet.next()) {
            int userId = resultSet.getInt("user_id");
            String surveyResult = resultSet.getString("survey_result");
            model.addRow(new Object[]{userId, surveyResult});
        }

        resultSet.close();
        statement.close();
        connection.close();
        */

        // For demonstration purposes, let's add sample data for all the users
        String[] users = {
        "alice", "bob", "username", "dave", "admin", "username",
        "username", "username", "michaelyang", "alicesmith", "username",
        "username", "maxwell", "samantha", "jim", "natalie", "michael",
        "lucas", "jessica", "rachel", "peter", "emma", "david",
        "anna", "stephanie", "robert", "katherine", "adam", "jane",
        "andrew"
    };

     // Random survey results
    String[] surveyResults = {
        "Excellent", "Good", "Average", "Poor", "Very Poor"
    };

    Random random = new Random();

    for (String user : users) {
        int randomIndex = random.nextInt(surveyResults.length);
        String randomResult = surveyResults[randomIndex];
        model.addRow(new Object[]{user, randomResult});
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "User", "Survey Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resultsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resultsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resultsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resultsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String selectedUsername = null;
                new resultsManager(selectedUsername).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
