/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cms.project;

import classes.cConnect;
import classes.cQuestions;
import classes.cUser;
import java.sql.*;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Jorg
 */
public class survey extends javax.swing.JFrame {
    
    private String[] questions;
    private int questionIndex;
    private int[] selectedValues; // Array to store selected values for each question

    // Radio button groups for each question
    private ButtonGroup[] buttonGroups;


    /**
     * Creates new form survey
     */
    public survey() {
        initComponents();
        initializeQuestions();
        initializeRadioButtons();
        displayQuestion(0);

    }
    
    // Initialize the survey questions
    private void initializeQuestions() {
        cQuestions questionHandler = new cQuestions();
        questions = questionHandler.getSurveyQuestions();
    }

    // Initialize the radio buttons and button groups
    private void initializeRadioButtons() {
        int numQuestions = questions.length;
        buttonGroups = new ButtonGroup[numQuestions];
        selectedValues = new int[numQuestions];

        // Create button groups and assign values for each question
        for (int i = 0; i < numQuestions; i++) {
            ButtonGroup group = new ButtonGroup();
            buttonGroups[i] = group;

            // Assign values to radio buttons
            JRadioButton[] buttons = {a, b, c, d, e, f, g}; // Assuming you have 7 radio buttons
            int numButtons = buttons.length;
            int valueStep = 10 / numButtons; // Divide the range of values equally

            for (int j = 0; j < numButtons; j++) {
                JRadioButton button = buttons[j];
                int value = (j + 1) * valueStep; // Assign values from 10 to 1
                button.setActionCommand(Integer.toString(value));
                group.add(button);
            }
        }
    }

    // Display the current question
    private void displayQuestion(int questionIndex) {
        questionsTxt.setText(questions[questionIndex]);

    // Check if it's the last question
    if (questionIndex == questions.length - 1) {
        nextBtn.setText("Finish");
    }
    }

    // Get the selected value for the current question
    private int getSelectedValue() {
        ButtonGroup group = buttonGroups[questionIndex];
        Enumeration<AbstractButton> buttons = group.getElements();

        while (buttons.hasMoreElements()) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return Integer.parseInt(button.getActionCommand());
            }
        }

        return -1; // Return -1 if no option is selected
    }

    // Save the selected value for the current question
//    private void saveSelectedValue() {
//            // Get the selected answer
//         // Get the selected value
//        int value = getSelectedValue();
//
//        // Save the value to the selectedValues array
//        selectedValues[questionIndex] = value;
//
//        // Move to the next question or handle survey completion
//        questionIndex++;
//        if (questionIndex < questions.length) {
//            displayQuestion(questionIndex);
//        } else {
//            // Handle survey completion
//            // ...
//            // Call the saveSurveyAnswers method to save the answers in the database
//            cQuestions questionHandler = new cQuestions();
//            cUser user = new cUser(username, email, jobRole, password);
//            questionHandler.saveSurveyAnswers(selectedValues, user.getUsername());
//        }
////    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        questionsTxt = new javax.swing.JLabel();
        a = new javax.swing.JRadioButton();
        b = new javax.swing.JRadioButton();
        c = new javax.swing.JRadioButton();
        d = new javax.swing.JRadioButton();
        e = new javax.swing.JRadioButton();
        f = new javax.swing.JRadioButton();
        g = new javax.swing.JRadioButton();
        nextBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        questionsTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionsTxt.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(questionsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(questionsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        a.setText("1");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        b.setText("2");

        c.setText("3");

        d.setText("4");

        e.setText("5");

        f.setText("6");

        g.setText("7");

        nextBtn.setText("NEXT");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(a)
                        .addGap(18, 18, 18)
                        .addComponent(b)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(c)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d)
                                .addGap(18, 18, 18)
                                .addComponent(e))
                            .addComponent(nextBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(f)
                        .addGap(18, 18, 18)
                        .addComponent(g)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a)
                    .addComponent(b)
                    .addComponent(c)
                    .addComponent(d)
                    .addComponent(e)
                    .addComponent(g)
                    .addComponent(f))
                .addGap(71, 71, 71)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        /// Move to the next question or handle survey completion
    questionIndex++;
    if (questionIndex < questions.length) {
        displayQuestion(questionIndex);
    } else {
        // Handle survey completion
        JOptionPane.showMessageDialog(this, "Thank you for completing the survey!");
        dispose(); // Close the survey screen
    }
    }//GEN-LAST:event_nextBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new survey().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a;
    private javax.swing.JRadioButton b;
    private javax.swing.JRadioButton c;
    private javax.swing.JRadioButton d;
    private javax.swing.JRadioButton e;
    private javax.swing.JRadioButton f;
    private javax.swing.JRadioButton g;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel questionsTxt;
    // End of variables declaration//GEN-END:variables
}
